Yo ug ot to ma ke ab ra nc h
Pebblz/FindersKeepers pull request #28
Opened 2021-02-08 07:15 UTC by pnaatz

2021-02-11 01:18 UTC, JackofAllTradez7 requested changes

2021-02-11 01:18 UTC, JackofAllTradez7 commented on Assets/Scenes/Main Game.unity
> +      value: 60
dont forget to change the time back

2021-02-18 22:28 UTC, pnaatz commented on Assets/Scenes/Main Game.unity
> +      value: 60
good save

2021-02-19 00:57 UTC, JackofAllTradez7 approved these changes
Good Job Patrick 😄

2021-02-20 02:55 UTC, merged